name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        include:
          - python-version: "3.9"
            python-path: "/opt/hostedtoolcache/Python/3.9.*/x64/bin/python"
          - python-version: "3.10"
            python-path: "/opt/hostedtoolcache/Python/3.10.*/x64/bin/python"
          - python-version: "3.11"
            python-path: "/opt/hostedtoolcache/Python/3.11.*/x64/bin/python"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ python3-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-xdist
        pip install optuna lightgbm xgboost catboost
        pip install --upgrade numpy pandas scipy scikit-learn yfinance
    
    - name: List installed packages
      run: |
        ${{ matrix.python-path }} -m pip list
    
    - name: Run tests
      run: |
        # Run tests with full traceback and output
        ${{ matrix.python-path }} -m pytest -v --cov=./ --cov-report=xml --tb=long --show-capture=all test_enhanced_model.py
        
        # Only run real stock prediction test if basic tests pass
        if [ $? -eq 0 ]; then
          ${{ matrix.python-path }} -m pytest -v --cov=./ --cov-append --cov-report=xml --tb=long --show-capture=all test_real_stock_prediction.py || true
        fi
    
    # Codecov upload - will only run if CODECOV_TOKEN is available
    - name: Check for Codecov token
      id: check_codecov
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ -n "${{ secrets.CODECOV_TOKEN }}" ]; then
          echo "codecov_available=true" >> $GITHUB_OUTPUT
        else
          echo "Codecov token not found, skipping upload"
          echo "codecov_available=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload coverage to Codecov
      if: steps.check_codecov.outputs.codecov_available == 'true'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        verbose: true

  deploy:
    name: Deploy to Cloud
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Cloud
      run: |
        # Add your deployment commands here
        echo "Deployment would happen here"
